title: Sun, Sea and Salt.
subtitle: MP's Blog
author: Matthew-P Rogers

remote_theme: chrisrhymes/bulma-clean-theme
#only if using bulma
paginate: 5
paginate_path: "/blog/page:num"

category_path: "categories/:cat"
category_layout: "category_index.html"

# theme: minima
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-category-pages

category_path: "/category/"
category_layout: "category_index.html"

description: MP's Wesbite idea...in its early stages
email: matthewpierrerogers@gmail.com
twitter_username: "@Rogers_M_P"
 

titles_from_headings:
  strip_title: true
  collections: true
  
footer_menu: footer_menu
permalink: /:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
      author: "MP Rogers"
